[Mission5/조수연] Project_Notion_VanillaJS 과제
prgrms-fe-devcourse/FEDC4-5_Project_Notion_VanillaJS pull request #3
Opened 2023-07-06 05:42 UTC by suyeon1218

# 📌 과제 설명 

요구사항에 따라 노션 클로닝 과제를 진행했습니다. 

## 페이지 설계

노션의 레이아웃에 따라 왼쪽 페이지와 오른쪽 페이지를 나눠 설계했습니다.

<img width="816" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4-5_Project_Notion_VanillaJS/assets/80307321/d8f3e712-60de-4210-b267-d998316dcc8a">

<img width="958" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4-5_Project_Notion_VanillaJS/assets/80307321/d6c7e583-53e5-4bb3-bf93-b70ac1008ecd">

## 컴포넌트 설계

### ListPage

ListPage 를 이루고 있는 컴포넌트는 다음과 같습니다.

<img width="1025" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4-5_Project_Notion_VanillaJS/assets/80307321/6e9a84e5-200b-4980-ab9f-dfbd8398d06b">

### EditPage

EditPage 를 이루고 있는 컴포넌트는 다음과 같습니다.

<img width="1037" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4-5_Project_Notion_VanillaJS/assets/80307321/e62aed70-51a3-40ca-a1bc-019a7136a768">

# 👩‍💻 요구 사항과 구현 내용 

## 기본 요구사항

- [x] 글 단위를 Document라고 합니다. Document는 Document 여러개를 포함할 수 있습니다.

- [x] 화면 좌측에 Root Documents를 불러오는 API를 통해 루트 Documents를 렌더링합니다.

- [x] Root Document를 클릭하면 오른쪽 편집기 영역에 해당 Document의 Content를 렌더링합니다.

- [x] 해당 Root Document에 하위 Document가 있는 경우, 해당 Document 아래에 트리 형태로 렌더링 합니다.

- [x] Document Tree에서 각 Document 우측에는 + 버튼이 있습니다. 해당 버튼을 클릭하면, 클릭한 Document의 하위 Document로 새 Document를 생성하고 편집화면으로 넘깁니다.

- [x] 편집기에는 기본적으로 저장 버튼이 없습니다. Document Save API를 이용해 지속적으로 서버에 저장되도록 합니다.

- [x] History API를 이용해 SPA 형태로 만듭니다.
  -  루트 URL 접속 시엔 별다른 편집기 선택이 안 된 상태입니다.
  -  /documents/{documentId} 로 접속시, 해당 Document 의 content를 불러와 편집기에 로딩합니다.

## ✨ App 페이지 

라우트로 SPA 동작을 담당한다.

Document List와 Document Content 의 연결을 담당한다.

- [x] Document List 클릭 시 Documnet Content 를 호출한다.

### history 로 SPA 만들기

- [x] 페이지를 바꾸면 각 url 을 url 창에 표시한다.
- [x] history API 로 뒤로가기, 앞으로 가기를 구현한다.

## ✨Document List 페이지

Root Document 리스트를 호출하여 출력하고, 해당 도큐먼트들의 하위 리스트들을 관리한다.

### 기본 구현

- [x] List Page 를 생성한다.

- [x] List 컴포넌트를 생성한다.
  - [x] li 태그 안에 + 토글 버튼과 > 토글 버튼을 생성한다.
  - [x] li 태그 안에 Document 의 제목을 출력한다.
  - [x] 토글 버튼이 아닌 제목을 클릭하면 해당 페이지를 렌더링 한다. 

### 하위 list 불러오기

- [x] > 토글 버튼을 클릭하면 하위 document 를 가져온다.
  - [x] 토글 버튼에 이벤트를 추가한다.
  - [x] 클릭한 document 의 하위 document 를 가져온다.
  - [x] open document 목록에 해당 document 를 추가한다.
  - [x] open document 에 맞춰 컴포넌트를 새로 렌더링 한다.

### 글 삭제

- [x] List 컴포넌트에 삭제버튼을 추가한다.
  - [x] li 태그 안에 삭제 버튼을 생성한다.
  - [x] 삭제버튼을 클릭하면 삭제 API 를 호출한다.
  - [x] 삭제가 완료되면 list 를 새로 그린다.

### 글 추가

- [x] + 버튼을 누르면 도큐먼트에 하위 doucment 를 생성한다.
 - [x] + 토글 버튼에 이벤트를 추가한다.
 - [x] 클릭한 document 에 하위 document 를 가져온다.
 - [x] 하위 document 에 새 document 를 추가한다.
 - [x] 새로운 편집 페이지를 생성한다.
 - [x] 새로운 편집 페이지를 모달 형태로 만든다.

## ✨ Document Content 페이지

어떤 이벤트에 의해 해당 도큐먼트의 내용을 그린다.

### 기본 구현

- [x] Edit Page 를 생성한다.
- [x] Edit Component 를 생성한다.
  - [x] 제목을 출력한다.
  - [x] 본문을 출력한다.

### 글 편집

- [x] Edit 컴포넌트에서 수정 기능을 추가한다.
  - [x] 디바운스로 자동저장 API 를 호출하여 저장한다.

## ✨ 추가 기능

- [x] div 와 contentEditable 을 이용하여 편집기능을 업그레이드 한다.
- [x] 편집기 최하단에는 현재 편집 중인 document 의 하위 document 링크를 렌더링한다.
- [x] 편집 시 제목을 수정하면 따라서 List 에 있는 제목도 수정한다.
- [x] 낙관적 업데이트를 적용한다.
- [x] 리팩토링을 한다.
  - [x] 변수 명 수정하기
  - [x] 컴포넌트 분리하기
  - [x] todo 목록 완성하기
  - [x] 예외처리 하기
- [x] CSS 작업을 한다.

# ✅ PR 포인트 & 궁금한 점

### 1. selectDocument 가 필요한 게 맞을까요?

- createDocument
- removeDocument

해당 메소드는 전부 API 와 관련이 있는 메소드로, 다음과 같이 관리하고 있습니다.

<img width="800" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4-5_Project_Notion_VanillaJS/assets/80307321/99fca628-ea17-44e3-96e8-f2fedcb39b9c">

ListPage 에서 create, remove 를 해주게 될 경우 App 클래스의 selectDocument 메소드를 위임받아 EditPage 에 필요한 데이터를 전달하게 됩니다.

제가 궁금한 것은 App 클래스의 selectDocument 가 중간에서 매개역할을 해주는데, 현재의 방식이 더 좋은지, 아니면 App 클래스에서 createDocument 와 removeDocument 를 관리하여 ListPage 로 전달해주는 것이 좋은지 궁금합니다.

### 2. 예외처리, 유효성 검사

예외처리와 유효성 검사를 하고 싶은데 어떤 부분에서 예외처리를 해주면 좋을지 몰라 쉽게 손을 대지 못했습니다. 어떤 예외처리를 더 신경쓰면 좋을지 여쭤보고 싶습니다. (validation 폴더는 현재 함수가 하나밖에 없으나 리팩토링을 하며 함수가 늘어날 거라 생각해서 굳이 분리해두었습니다...)

### 3. 추가 기능

추가 기능 중 다음과 같은 기능이 있었습니다.

> 편집기 내에서 다른 Document name을 적은 경우, 자동으로 해당 Document의 편집 페이지로 이동하는 링크를 거는 기능을 추가합니다.

아무리 생각해도 구현할 방법이 생각나지 않아 해당 추가 기능만 남겨둔 상태인데 혹시 구현 아이디어가 있으시면 조언부탁드립니다...! 

### 4. 그 외

- 일관성이 지켜졌는지
- 변수명이 헷갈리진 않는지
- 파일 분리가 적절한지
- 더 반영하면 좋을 부분이 있는지

프로젝트 규모가 커지면서 신경썼음에도 놓친 부분이 많다고 생각합니다! 제가 적은 것 외에도 최대한 많은 조언 부탁드립니다!

2023-07-10 01:26 UTC, backward99 reviewed
노션 클로닝 잘 구경?하다 갑니다. 목록 위에 마우스를 올리면 버튼 나오는 것 까지..! 저의 불성실함을 반성하게 되네요. 항상 궁금한 점에 대해서 리뷰를 남기지 못하는 점 죄송합니다.. 이번 과제도 수고하셨습니다!

2023-07-10 01:26 UTC, backward99 commented on src/components/ListPage/DocumentList.js
> +      }
li 사이 부분을 어쩌다 보니 클릭하게 되었는데 오류가 발생했었습니다. li사이 부분을 클릭하게 되면 ul이 선택되어서 79번 라인의 li가 존재하지 않게 됩니다. $li의 존재?에 따른 실행 여부도 추가하면 좋을 것 같습니다!

2023-07-10 01:26 UTC, backward99 commented on src/page/EditPage.js
> +  };
타이틀은 왜 입력할 때마다 api를 호출했는지 궁금합니다!

2023-07-10 01:26 UTC, backward99 commented on src/page/EditPage.js
> +}
render에 new를 사용하여 DocumentContent와 ChildList를 만드셨고, EditPage의 setState에서 render를 계속해서 호출하고 있습니다. 이 때 EditPage의 setState에서 DocumentContent, ChildList의 setState를 사용하여 변경하는 방법도 있다고 생각했는데 new를 사용해서 매번 새로운 DocumentContent와 ChildList를 만드는 이유가 있을까요?

2023-07-10 01:26 UTC, backward99 commented on src/components/EditPage/DocumentContent.js
> +  };
제가 확인했을 때는 DocumentContent의 setState는 사용되지 않는 것 같습니다!

2023-07-10 10:29 UTC, perfumeplaylist reviewed
## 느낀점
1. 수연님 코드를 보면서 진짜 많이 생각하시고 고민한 흔적이 느껴져서 코드를 읽는데 일관성이랑 가독성 부분에서 너무 좋았습니다.
2. UI를 고려한 부분에서 많은 감동을 받았습니다!
3. 많이 배우고 코드 많이 보면서 성장하겠습니다. 이런 코드리뷰 할 기회를 주셔서 감사합니다!

2023-07-10 10:29 UTC, perfumeplaylist commented on src/App.js
> +import { getRootAPI, getContentAPI } from './utils/API.js';
getContentAPI 함수는 이 컴포넌트에서 이용을 안하는것 같은데 지워보이는게 좋아보입니다!

2023-07-10 10:29 UTC, perfumeplaylist commented on src/components/EditPage/DocumentContent.js
> +    $div.focus({ preventScroll: true });
오 focus메소드에 이런 매개변수가 있는지 몰랐어요! 이걸 이용하셔서 UI관점으로 향상 되는것 같습니다!

2023-07-10 10:29 UTC, perfumeplaylist commented on src/components/ListPage/DocumentList.js
> +  };
초기화해주는 메소드 너무 좋은데요??!

2023-07-10 10:29 UTC, perfumeplaylist commented on src/components/ListPage/DocumentList.js
> +    this.clickListEvent();
render가 될때마다 이벤트가 할당 되는것 같습니다!constructor에 넣는건 어떠신가요??!

2023-07-10 10:29 UTC, perfumeplaylist commented on src/components/ListPage/DocumentList.js
> +    }
오 예외처리 완전 감동입니다:)

2023-07-10 10:29 UTC, perfumeplaylist commented on src/page/EditPage.js
> +      documentContent: documentContent
이런식으로 하나로 합칠수 있을것 같습니다!
`const nextState = {
      ...this.state,
      documentContent,
    };`

2023-07-10 10:29 UTC, perfumeplaylist commented on src/page/ListPage.js
> +    };
이런 데이터는 따로 파일로 만들어서 메소드로 관리해주는게 추상적이면서 다른 곳에서도 잘 쓰일것 같습니다!

2023-07-10 10:29 UTC, perfumeplaylist commented on src/utils/API.js
> +}
한 메소드로 관리 할 수 있을것 같습니다!
` export const getAPI = async (pathname = "") => {
   try {
    const response = await fetch(
      ${API_END_POINT}${pathname.length ? pathname : ""}, ...`

2023-07-10 14:27 UTC, SongInjae reviewed
- 개인적으로 이번에도 class로 구현하는 것이 인상 깊었습니다!
- 각 기능별로 세부적으로 쪼개서 파일 관리를 잘 하신 것을 보고 배웠습니다.
- 코드가 깔끔하게 정리되어 있어 보기 좋았습니다.

2023-07-10 14:27 UTC, SongInjae commented on src/utils/API.js
> +      const data = response.json();
여기서 data라는 변수에 들어있는 값인 response.json()이 공통적으로 자주 쓰이지 않음에도 변수명으로 선언해서 return 해야하는 것인지 궁금합니다!

2023-07-10 14:27 UTC, SongInjae commented on src/utils/StorageHandler.js
> +    return openState === null ? false : true;
이곳에서도 변수명을 선언한 뒤에 사용하는 방식이 아니여도 될 것 같습니다!

2023-07-10 14:27 UTC, SongInjae commented on src/utils/Validation.js
> +
validation 부분에 title에 대한 값에 대하여 XSS공격 방지코드가 추가되면 좋을 것 같습니다! content에 대해서는 공격이 들어가지는 않지만 title에는 공격이 허용됩니다!

2023-07-10 17:10 UTC, eugene028 reviewed
제 생각에 수연님은... 너무 허전한 거 같습니다...

명불허전....💛
class로 컴포넌트 구성하신 부분 보면서 이번에야말로!! 객체 지향적인 코드를 작성하기 위하여 많은 고민을 하신 것 같다는 생각이 들어 저도 꼼꼼하게 코드를 읽어보았던 같아요.
이번 노션 클론 프로젝트를 하는 수연님을 옆에서 보다 보니.. 예쁘게 갈고 닦아진 고퀄리티의 유리 도자기를 만들고 있는 장인 느낌을 받았어요..헤헤 작성한 코드를 귀찮아!! 하면서 그냥 날려 보지 않고 여러번 두드려 보고 같은 부분에 대해서도 다양한 방법으로 고민하시는 것 같아서 많이 배워갑니다 수연님!!!!!!!!
파이팅!!!!!! 🍀

2023-07-10 17:10 UTC, eugene028 commented on src/App.js
> +  reflectTitleChange = async() => {
해당 함수는 `listPage`에서 상태를 관리해줘도 좋을 것이라고 생각이 드는데, App.js에서 관리하는 이유가 따로 있을까요?!

2023-07-10 17:10 UTC, eugene028 commented on src/page/ListPage.js
> +  removeDocument = async (documentId) => {
정호님과 비슷한 의견으로, Page는 페이지의 랜더링과 관련한 부분만 신경쓰고, 데이터를 조작하는 함수는 다른 파일로 분리하는 것이 좋습니다 :)
그러나 현재 바닐라 Js를 이용하여 구현하다 보니 아직은 이런 디테일까지 모두 챙기기에는 어려울 수 있다고 생각됩니다 헤헤

2023-07-10 17:10 UTC, eugene028 commented on src/components/ListPage/DocumentList.js
> +    this.$ul.innerHTML = `
`this.state`라는 반복적인 코드가 많이 사용되므로 구조 분해 할당을 사용하여 한번 코드를 정리해주는 것도 좋을 것 같아요!

2023-07-10 17:10 UTC, eugene028 commented on src/components/ListPage/DocumentList.js
> +      new NoneChild(this.$ul, this.state.depth + 1);
👍👍👍

2023-07-10 17:10 UTC, eugene028 commented on src/components/ListPage/DocumentList.js
> +      if ($li.className.startsWith('document-li') === true && $button === null) {
의도하지 않은 부분이 선택되었을 때, 이벤트 콜백함수에서 빠져나오는 `return`문을 작성하면 쉽게 리팩토링 할 수 있을 것 같습니당!!!

2023-07-10 17:10 UTC, eugene028 commented on src/components/ListPage/DocumentList.js
> +    if ($button.className === 'open-toggle-button') {
클래스명 너무 깔끔해서 마음이 편안해집니다 수연님....🥹🫶

2023-07-10 17:10 UTC, eugene028 commented on style/index.css
> +.depth-04 {
클래스명에 존재하는 숫자를(01, 02 ...) 매개변수로 삼아서 `padding-left`를 `15px`만큼 늘려주는 등차수열 형식으로 인라인 스타일로 작성한다면 중복되는  코드를 줄일 수 있다고 생각됩니다!

2023-07-11 06:57 UTC, suyeon1218 commented on src/components/ListPage/DocumentList.js
> +      }
와 정말이네요! 오류 찾아주셔서 감사합니다 ><!!

2023-07-11 07:01 UTC, suyeon1218 commented on src/page/EditPage.js
> +  };
타이틀의 경우 디바운싱을 넣으면 ListPage 에 바로바로 반영이 되지 않아서입니다! 사용자 경험? UI 적 요소를 위해 성능적 측면을 일부 포기했습니다 ㅎ_ㅎ...!

2023-07-11 07:05 UTC, suyeon1218 commented on src/page/EditPage.js
> +}
오… 지호님 말대로 Page 에서 render 를 실행시키기 보다 컴포넌트에서 setState 를 통해 업데이트를 하는 게 낫겠군요! 좋은 의견 감사합니다!

2023-07-11 07:44 UTC, suyeon1218 commented on src/page/EditPage.js
> +}
내친김에 App 에서도 setState 를 통해 EditPage 를 관리하게끔 했습니다! 의견 너무너무 감사합니다~! 코드의 일관성을 해치고 있었네요 ㅠ_ㅠ

2023-07-11 07:45 UTC, suyeon1218 commented on src/components/EditPage/DocumentContent.js
> +  };
원래는 일관성을 위해 넣었는데 지호님께서 새 컴포넌트를 만들지 않고 setState 를 사용하는 게 어떠냐고 하셔서 수정했습니다! 감사합니다!

2023-07-11 07:45 UTC, suyeon1218 commented on src/App.js
> +import { getRootAPI, getContentAPI } from './utils/API.js';
감사합니다!! 수정했습니다!

2023-07-11 07:46 UTC, suyeon1218 commented on src/components/EditPage/DocumentContent.js
> +    $div.focus({ preventScroll: true });
저도 블로그 참고했습니다.. ㅎㅎ 자세히 알아봐야겠군요!

2023-07-11 07:48 UTC, suyeon1218 commented on src/components/ListPage/DocumentList.js
> +    this.clickListEvent();
오... 이전에도 이벤트를 매번 할당한다는 지적을 받았을 때 무슨 의미인지 몰랐는데 element 를 삭제하고 새로 생성하지 않는 이상 그냥 한번만 이벤트를 할당하면 되는거군요!! 좋은 리뷰 감사합니다!!

2023-07-13 02:00 UTC, pocojang requested changes
안녕하세요
수연님

정말 감동적인 PR 이군요!!
커밋도 엄청 나누시며 요구사항을 보셨다는 티가 나네요.
꼼꼼하게 잘 구현하고 정리해주셔서 잘 봤습니다

## 피드백

### null

`null`을 사용하시는 것 자체는 좋지만 너무 많다보니 핸들링이 많이 되네요
JS에서 null vs undefined 무엇이 좋을지 고민해보시면 좋겠어요!
정답은 없으니까 공부해보시고 나만의 기준을 잡아보세요

### 구조

조금 애매한 것 같아요.
전통적으로 흔히쓰이는 구조랑은 달라서 그렇게 보일 수 있는데 페이지와 컴포넌트는 한 결이 달라보이고요.

또한 페이지와 컴포넌트라는 곳에서 많은 로직을 들고 있어서 분리해볼 수 있는 방법을 고민해보시고 뭘 분리할까도 생각해보시면 좋겠습니다~
나머지는 질문에서 다룰게요!

### 횡단 관심사

유틸로 만들어주신 코드들에 도메인의 흔적이 가득합니다.
즉 횡단 관심사를 뽑아내서 노션이 아닌 다른 프로젝트에서도 사용할 수 있도록 해보시는 훈련을 해보시면 좋습니다


## ✅ PR 포인트 & 궁금한 점

### 1. selectDocument 가 필요한 게 맞을까요?

저도 좀 애매한 것 같아요.
요 부분 어떻게 확장할지 한번 고민해보세용

### 2. 예외처리, 유효성 검사

예외는 어디서 던지고 어디서 받느냐
사용자를 위한 에러, 함께 일하는 개발자를 위한 에러

이런 관점으로 챙기기 위해 노력해보시면 점점 좋아지실겁니다

### 3. 추가 기능

잘못된 시도는 아니니까 다른 분들의 구현 방법을 많이 확인해보세요!

### 4. 그 외

내용은 이미 다 적었으나 `Prettier`, `ESLint`는 꼭 사용해보시는게 좋겠습니다.
지금은 자동 포맷팅이 아닌 것처럼 보여서요~!

2023-07-13 02:00 UTC, pocojang commented on index.html
> +</html>
EOL은 여전히 반복되는군요 ㅠㅠ

2023-07-13 02:00 UTC, pocojang commented on src/App.js
> +    window.addEventListener('popstate', this.route);
이런 경우 항상 ㄷ 문제를 조심하세요!

2023-07-13 02:00 UTC, pocojang commented on src/App.js
> +  selectDocument = (selectedDocumentId) => {
```suggestion
  selectDocument = (selectedDocumentId = null) => {
```
`JS`에서는 `undefined`를 주의해야되기때문에 `null`만 체크하는 것도 위험합니다 ㅎㅎ

2023-07-13 02:00 UTC, pocojang commented on src/components/EditPage/ChildList.js
> +      this.selectDocument(this.state[index].id);
```suggestion
      this.selectDocument(this.state[index]?.id ?? 없다면 무언가를..?!);
```

2023-07-13 02:00 UTC, pocojang commented on src/components/EditPage/DocumentContent.js
> +    this.$div.addEventListener('keyup', (event) => this.saveEdit(event.target));
평소와는 다르게 이번에는 화살표 함수로 넘겨주셨군요?!

2023-07-13 02:00 UTC, pocojang commented on src/components/ListPage/DocumentList.js
> +  constructor($target, initialState, selectDocument, createDocument, removeDocument) {
매개변수를 이렇게 쫘르륵 받으면 사용 부에서는 많이 헷갈리지 않을까요?

2023-07-13 02:00 UTC, pocojang commented on src/components/ListPage/DocumentList.js
> +    if (this.state.depth === 9) {
`9`가 무엇일까요 🤔

2023-07-13 02:00 UTC, pocojang commented on src/page/EditPage.js
> +  }
아닛.. 이건 무엇때문에 필요한걸까요?

2023-07-13 02:00 UTC, pocojang commented on src/page/ListPage.js
> +  constructor($target, initialState, selectDocument) {
마찬가지로 3개 이상 인자를 받을떄는 객체로 받는게 더욱 관리하기 쉽답니다.

2023-07-13 02:00 UTC, pocojang commented on src/page/ListPage.js
> +    this.$div.className = 'list-page-container';
표준 문법을 이용하시죠!
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

2023-07-13 02:00 UTC, pocojang commented on src/utils/API.js
계속 반복되는 코드들은 어떻게 분리할 수 있을까요?

2023-07-13 02:00 UTC, pocojang commented on src/utils/StorageHandler.js
> +    return openState === null ? false : true;
```suggestion
    return localStorage.getItem(id);
```

2023-07-13 02:00 UTC, pocojang commented on style/nomalize.css
이건 왜 필요하셨을까요?!

2023-07-13 02:00 UTC, pocojang commented on style/index.css
컬러 관리가 전혀~~ 안되고 있네요!
팔레트 관리를 시작하는게 어떨까요?

2023-07-13 02:00 UTC, pocojang commented on src/utils/Route.js
> +  window.dispatchEvent(new CustomEvent(ROUTER_CHANGE_EVENT), params);
오.. 엄청난 시도군요!

2023-07-13 02:00 UTC, pocojang commented on index.html
> +    <link rel="stylesheet" href="/style//nomalize.css">
😮

2023-07-17 05:29 UTC, suyeon1218 commented on src/utils/API.js
> +      const data = response.json();
저도 고민해 봤는데 당장 수정이나 삭제 API 의 응답 메소드는 사용하고 있지 않지만 코드에서 오류를 발견하기 위해 응답을 받아야할 때도 있어서 자바스크립트 내에서 확인할 수 있도록 json 으로 return 을 해야할 것 같습니다!

2023-07-17 05:50 UTC, suyeon1218 commented on src/utils/Validation.js
> +
헉 그렇군요..!! 안 그래도 인재님께서 남겨주신 XSS 공격 당했습니다...ㅋㅋㅋㅋ 방어코드를 넣거나 div editable 로 수정해야겠어요~

2023-07-17 06:14 UTC, suyeon1218 commented on src/App.js
> +  reflectTitleChange = async() => {
App 이 ListPage 와 DocumentPage 를 중재하기 때문입니다! 다만 유진님께서 말씀하신 것처럼 listPage 에서 state 를 관리하기 때문에 rootAPI 를 호출하는 로직을 listPage 내에서만 관리하도록 수정했습니다!

2023-07-17 06:24 UTC, suyeon1218 commented on src/page/ListPage.js
> +  removeDocument = async (documentId) => {
react 들어가면 꼭... 더 깔끔한 코드를 보여드리겠습니다 🔥

2023-07-17 06:25 UTC, suyeon1218 commented on src/components/ListPage/DocumentList.js
> +    this.$ul.innerHTML = `
좋은 리뷰 감사합니다~!! 반영할게요!!

2023-07-17 06:31 UTC, suyeon1218 commented on src/components/ListPage/DocumentList.js
> +      if ($li.className.startsWith('document-li') === true && $button === null) {
유진님 덕에 한층 더 깔끔한 코드를 작성하게 되었습니다... 👍

2023-07-17 06:40 UTC, suyeon1218 commented on style/index.css
> +.depth-04 {
!! 왜 이 방법을 생각하지 못했을까요 감사합니다 유진님... ㅠㅠㅠㅠ

2023-07-17 08:04 UTC, merged

2023-07-17 08:22 UTC, SongInjae commented on src/utils/API.js
> +      const data = response.json();
오옹 확장성 때문에 변수를 따로 선언하신건가용??

2023-07-17 08:23 UTC, SongInjae commented on src/utils/Validation.js
> +
ㅋㅋㅋㅋ 해커가 왜 해킹하는지 알 것 같습니다😎 재밌네요🥸