[Mission5/송인재] Project_Notion_VanillaJs 과제
prgrms-fe-devcourse/FEDC4-5_Project_Notion_VanillaJS pull request #6
Opened 2023-07-06 08:39 UTC by SongInjae

## 📌 과제 설명 
<img width="1440" alt="스크린샷 2023-07-06 오후 5 22 22" src="https://github.com/prgrms-fe-devcourse/FEDC4-5_Project_Notion_VanillaJS/assets/44944877/14a71c2a-9483-4785-acfd-69123dcc8a3f">

**`개발자들이라면 떼놓을 수 없는 "Notion"을 클론코딩 했습니다!!`**

## 👩‍💻 요구 사항과 구현 내용 

- 글 단위를 Document라고 합니다. Document는 Document 여러개를 포함할 수 있습니다.

- 화면 좌측에 Root Documents를 불러오는 API를 통해 루트 Documents를 렌더링합니다.
  - Root Document를 클릭하면 오른쪽 편집기 영역에 해당 Document의 Content를 렌더링합니다.
  - 해당 Root Document에 하위 Document가 있는 경우, 해당 Document 아래에 트리 형태로 렌더링 합니다.
  - Document Tree에서 각 Document 우측에는 + 버튼이 있습니다. 해당 버튼을 클릭하면, 
  클릭한 Document의 하위 Document로 새 Document를 생성하고 편집화면으로 넘깁니다.

- 편집기에는 기본적으로 저장 버튼이 없습니다. Document Save API를 이용해 지속적으로 서버에 저장되도록 합니다.

- History API를 이용해 SPA 형태로 만듭니다.
  - 루트 URL 접속 시엔 별다른 편집기 선택이 안 된 상태입니다.
  - /documents/{documentId} 로 접속시, 해당 Document 의 content를 불러와 편집기에 로딩합니다.

### Sidebar 컴포넌트
- 각 사이드 바에 자식 사이드바를 만들 수 있는 기능
- 선택한 사이드바를 표시해주는 기능
- 사이드바를 삭제할 수 있는 기능

### Content 컴포넌트
- 사이드바에 해당하는 내용을 작성할 수 있는 기능
- 작성한 내용의 굵기, 이탤릭체, 정렬을 할 수 있는 기능
- 작성한 사이드바의 제목과 내용이 자동으로 수정되는 기능
- 사이드바의 제목에 낙관적 업데이트가 되도록 하는 기능

## ✅ PR 포인트 & 궁금한 점 
1. 함께 개발하는 개발자 동료라면, 이러한 점이 개선되었으면 좋겠다는 저의 습관이 있는지 궁금합니다!
2. 불필요한 코드들이 존재하는지 궁금합니다!
3. 코드를 조금 더 깔끔하게 짤 방법이 있는지 궁금합니다!
4. 이러한 부분을 추가, 보완했으면 좋겠는 부분들이 있는지 궁금합니다!
5. 최대한 필요없는 부분을 넣지 않고자 했는데, 너무 간추려서 가독성이 떨어지고 있는 것인지 궁금합니다!

2023-07-09 04:40 UTC, suyeon1218 commented
인재님 노션 클론 코딩 하느라 수고하셨습니다!! 제출 날 저희 다 던져놓다 시피 했어서 너무 웃겼어요 😄

2023-07-09 04:42 UTC, suyeon1218 commented on src/Content.js
> +import Editor from "./editor.js";
Editor.js 로 바꿔줘야 하지 않을까요!

2023-07-09 04:43 UTC, suyeon1218 commented on src/App.js
> +  const { pathname } = window.location;
대게 const 를 let 보다 먼저 선언해주는 게 클린 코드라고 알고 있어요!

2023-07-09 04:44 UTC, suyeon1218 commented on src/App.js
> +  let timer = null;
App.js 내에선 timer 가 사용되지 않는 것처럼 보입니다...! 👀

2023-07-09 04:45 UTC, suyeon1218 commented on src/App.js
> +  const [, check, contentId] = pathname.split("/");
이런 식으로 구조분해 할당을 하셨군요...! 저는 왜 이 방법이 생각이 안 났던 걸까요 ㅠㅠ 좋은 팁 감사합니다!

2023-07-09 04:46 UTC, suyeon1218 commented on src/App.js
> +    onEditing: async (title, content) => {
onChange 는 밖으로 함수를 만들어 따로 빼주셨는데 onEditing 의 경우 함수를 따로 만들지 않으신 이유가 있으실까요!

2023-07-09 04:50 UTC, suyeon1218 commented on src/App.js
> +  let $notionContent = document.querySelector(".notion-content");
$notionContent 의 프로퍼티를 제외하곤 $notionContent 자체가 바뀌지 않는 것 같은데 const를 사용하심이 어떠실까요~!

2023-07-09 04:55 UTC, suyeon1218 commented on src/Sidebar.js
> +function navDraw(documents, $target, fetchSidebar, onChange) {
오... SideBar 에 쓰이는 컴포넌트들을 SideBar.js 폴더 내에 정의해주셨군요! 이런 방법이 어떨땐 더 유용할 거 같아요! 배워갑니다~

2023-07-09 04:58 UTC, suyeon1218 commented on src/modal.js
> +    const input = document.getElementById("modal-input-title");
도중에 새로운 변수를 선언하는 것보다 코드 상단에서 사용할 변수를 모두 선언하는 게 더 좋을 것 같습니다!

2023-07-10 02:22 UTC, backward99 reviewed
인재님이 api호출 오류를 화면에 표시하는 기능을 작성해 주신 덕분에 어떤 부분에서 오류가 발생했는지 알게 되었습니다. 실험?도 해봤는데 제가 다녀간 흔적이 좀 많이 남아있을지도 모릅니다.. 노션 과제 수고 많으셨습니다!

2023-07-10 02:22 UTC, backward99 commented on src/Sidebar.js
> +    });
15번째 라인에서 추가한 이벤트와 동시에 이벤트가 발생됩니다! 의도치 않은 내용도 같이 실행 될 수 있을 것 같습니다! 이벤트 위임을 이용하거나 이벤트가 하나 실행 되었을 때 나머지 이벤트는 발생하지 않게 하는 처리를 해주는 것은 어떨까요?

2023-07-10 02:22 UTC, backward99 commented on src/modal.js
> +  const $submitModal = document.getElementById("submit-modal");
querySelector를 사용하실 때도 있고 getElementById를 사용하실 때도 있는데 그렇게 사용하신 이유가 있는지 궁금합니다!

2023-07-10 02:23 UTC, backward99 commented on src/Sidebar.js
> +    });
1. 이벤트 타겟의 가장 가까운 부분의 list를 고르는 것이 좋아 보입니다! 목록들을 클릭해 보다가 우연히 발견하게 되었는데, 밖을 둘러싸고 있는 div가 선택될 때 id가 null이 되어 오류가 발생합니다! 
2. list 안의 list에 이벤트의 중복이 발생합니다!

2023-07-10 04:08 UTC, suyeon1218 commented on src/Sidebar.js
> +function navDraw(documents, $target, fetchSidebar, onChange) {
navDraw 함수가 너무 많은 일과 컴포넌트를 관리하고 있는 것 같아요. Modal 이나 ButtonModal 컴포넌트를 정의해주신 것처럼 navDraw 컴포넌트 안의 함수들도 분리해보시는 건 어떨까요?!

2023-07-10 18:30 UTC, eugene028 reviewed
항상 긍정 에너지를 전달해주시는 인재님 👼 이번 프로젝트 정말 수고 많으셨습니다!
프로젝트에 대한 규모가 이전보다 크기 때문에 모든 파일이 `src` 폴더 안에 있기보다는 컴포넌트와 페이지, 함수, api 모듈별로 구분하는 연습을 다음 리팩토링 때 반영하여 연습해 보아도 좋을 것 같아요 👍
파이팅입니다!!!

2023-07-10 18:30 UTC, eugene028 commented on index.css
> +    /*background-color: lightgray;*/
사용하지 않는 코드는 제출 전 한번 확인하기!! 😉

2023-07-10 18:30 UTC, eugene028 commented on index.html
> +        <title>잉재의 노션 클로닝 프로젝트</title>
ingjae....

2023-07-10 18:30 UTC, eugene028 commented on src/App.js
> +  if (check) {
`documents` 라는 문자열이 `check` 안에 들어가고, 문자열이 있을 경우에는 자동적으로 `boolean` 값이 `true`가 되도록 설계하신 게 맞을까요??!

2023-07-10 18:30 UTC, eugene028 commented on src/Content.js
> +        if (divElement.children[i].tagName === "SPAN") {
오 `tagName` 이라는 메서드는 처음 보네요! 대문자만 쓰여서 신기합니다 🤓

2023-07-10 18:30 UTC, eugene028 commented on src/Content.js
> +      for (let i = 0; i < divElement.children.length; i++) {
`forEach`와 그에 기본으로 주어지는 `index`를 사용하면 조금 더 간결한 코드를 작성할 수 있을 것 같습니다! :)

2023-07-10 18:30 UTC, eugene028 commented on src/Content.js
> +          this.setState(nextState);
`this.setState(nextState)`는 중복되는 코드이므로 큰 if문 안에 한번만 작성해도 될 것 같습니다!

2023-07-10 18:30 UTC, eugene028 commented on src/Editor.js
> +    document.execCommand(e.target.getAttribute("data-command"));
오 `execCommand` 메서드에 대해서 공부해보아야 겠군요!
간결하게 Rich한 에디터를 작성할 수 있음을 발견했습니다... 인재님 짱

2023-07-10 18:30 UTC, eugene028 commented on src/Sidebar.js
> +      onChange(e.target.parentNode.getAttribute("data-id"));
`onChange` 함수에 바로 인자를 넘겨주는 것도 좋지만, 코드를 읽었을 때 한번에 이해하기 위해서는 명시적인 변수에 정의해준 뒤에 파라미터로 넘겨주는 것이 좋을 것 같아요 ㅎㅎ

2023-07-11 00:53 UTC, perfumeplaylist reviewed
##느낀점
1. 인재님 코드가 직관적으로 하셔서 코드 리뷰하는데 술술 읽히고 이해가 바로바로 갔습니다!
2. 모델창을 만드신거 보고 감동했습니다 👍 
3. 나중에 유지보수를 위해서 컴포넌트가 필요한 메소드를 잘 정의했으면 더 좋겠다는 생각이 들었습니다!

2023-07-11 00:53 UTC, perfumeplaylist commented on src/App.js
> +    $notionContent.style.display = "flex";
수정 할때마다 style이 설정되시는것 같은데 클래스로 따로 관리해서 toggle 기능으로 관리할수 있다고 생각하는데 어떠신가요??!

2023-07-11 00:53 UTC, perfumeplaylist commented on src/Sidebar.js
> +    });
toggle 메소드 이용해보시는거 추천드립니다!
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle

2023-07-11 00:53 UTC, perfumeplaylist commented on src/Sidebar.js
> +}
이 버튼만 이렇게 처리해주신 이유가 있으실까요??!

2023-07-11 00:53 UTC, perfumeplaylist commented on src/modal.js
> +  $submitModal.addEventListener("click", () => {
유저가 엔터를 할 수 있어서 엔터 키 이벤트 처리도 해주시는게 유저입장에서도 좋을것 같습니다!

2023-07-15 12:42 UTC, pocojang requested changes
안녕하세요
인재님!

다른 분들이 리뷰를 아주 잘 해주셔서 할게 별로 없었네요 ㅎㅎ
그래도 궁금한게 있으면 디엠 주세요

## 피드백

- API 분리 시도 아주 좋아요. 조금은 아쉬운 면이 있지만 그래도 좋은 방향의 구현이네요

### 함수로 생성자 함수를 구현한 이유가 무엇일까요?

조금 아쉽네요
과거의 JS는 `Instance` 생성을 돕는 `Class`가 존재하지 않아서 이런 생성자 함수를 사용했었습니다.
여기서 몇가지 중요 포인트를 뽑아본다면요.
이 두가지인데 꼭 알고 넘어가셨으면 좋겠습니다.

- 이미 대체할 수 있는 Class가 등장했는데 굳이 생성자함수를 사용해야했을까?
- 이렇게 될 경우 메서드 메모리가 어떻게 될까?

이외에 중요한 포인트는 코멘트 리뷰 남겨놨습니다.

## Q&A

### Q1. 함께 개발하는 개발자 동료라면, 이러한 점이 개선되었으면 좋겠다는 저의 습관이 있는지 궁금합니다!

복잡한 if문을 어떻게 정리할 수 있을까요?
컴포넌트 내부의 코드들을 어떻게 구분할 수 있을까요?
코드가 주르르르륵 나열되었다는 느낌이 종종 듭니다
이러한 습관을 개선해보면 좋겠어요

### Q2. 불필요한 코드들이 존재하는지 궁금합니다!

은근히 중복코드들이 반복되고 있어요!
의식적인 개선을 해보시는게 어떨까요?

### Q3. 코드를 조금 더 깔끔하게 짤 방법이 있는지 궁금합니다!

의식적인 개선 방법을 고민해보시는게 좋아요.
현재는 분기문 최적화만 고민해보셔도 충분하고요.
구역을 잘 쪼개어 분리하는게 좋을 것 같습니다.


### Q4. 이러한 부분을 추가, 보완했으면 좋겠는 부분들이 있는지 궁금합니다!

- 분기문 줄이기
- 생성자 함수에 대해 학습하기입니다


### Q5. 최대한 필요없는 부분을 넣지 않고자 했는데, 너무 간추려서 가독성이 떨어지고 있는 것인지 궁금합니다!

음.. 함수 하나하나가 하는 덩어리가 너무 클때가 있어요.
그래서 필요없는 부분은 적지만 함수 하나하나가 덩치가 커보입니다 ㅠㅠ

---

지호님과 유사한 코드가 많았던 것 같은데요.
비슷한 리뷰 내용이 있으니 교차해서 확인해보세요 :)

2023-07-15 12:42 UTC, pocojang commented on index.html
> +</html>
😢

2023-07-15 12:42 UTC, pocojang commented on src/Content.js
> +  let timer = null;
이건 왜 상태가 아닐까요?

2023-07-15 12:42 UTC, pocojang commented on src/Content.js
> +    timer = setTimeout(async () => {
코드가 점점 복잡해지네요
어떻게하면 정리할 수 있을까요?
기획적인 요구사항이 추가된다면? 누군가 여기서 생긴 버그를 수정한다면 관리가 어려울 것 같습니다.

2023-07-15 12:42 UTC, pocojang commented on src/Editor.js
> +  $target.appendChild($editor);
`append()`로 간편하게 줄이실 수 있습니다!

2023-07-16 11:36 UTC, SongInjae commented on src/Content.js
> +import Editor from "./editor.js";
감사합니다😊

2023-07-16 11:36 UTC, SongInjae commented on src/App.js
> +  const { pathname } = window.location;
헉 그런 부분도 있었군요! 감사합니다😊

2023-07-16 11:43 UTC, SongInjae commented on src/App.js
> +  let timer = null;
예리하시군요🙈 감사합니다😊

2023-07-16 11:44 UTC, SongInjae commented on src/App.js
> +  const [, check, contentId] = pathname.split("/");
저도 어쩌다 운좋게 떠올랐어요🥸

2023-07-16 11:45 UTC, SongInjae commented on src/App.js
> +    onEditing: async (title, content) => {
onChange의 경우에는 밖에서 함수 자체로 사용하기 때문에 빼뒀습니다:) 모두다 빼놓는 것이 좋을까요?

2023-07-16 11:47 UTC, SongInjae commented on src/App.js
> +  let $notionContent = document.querySelector(".notion-content");
헉 그러네요! 왜 let으로 썼지....☠️

2023-07-16 12:09 UTC, SongInjae commented on src/Sidebar.js
> +function navDraw(documents, $target, fetchSidebar, onChange) {
네 제가 봐도 메인 함수만큼의 무거운 작업들을 하고 있었던 것 같습니다! 좋은 조언 감사합니다🙏

2023-07-16 12:11 UTC, SongInjae commented on src/modal.js
> +    const input = document.getElementById("modal-input-title");
변수끼리 한 번에 선언하니까 코드가 더 깔끔한 것 같습니다! 감사합니다🙏

2023-07-16 12:48 UTC, SongInjae commented on src/modal.js
> +  const $submitModal = document.getElementById("submit-modal");
아직 '어느 것을 고정적으로 써야겠다'라고 생각이 들지 않아서, 생각나는 것들로 사용했던 것 같습니다! 통일하는 것이 깔끔할 것 같습니다! 감사합니다:)

(+ 지호님의 이 리뷰를 보고 querySelector가 있는데 왜 getElementByID가 있는거지 하고 둘의 차이점을 찾아봤는데 getElementById가 querySelector보다 성능면에서 더 좋다고 합니다! 그래서 getElementById를 선호하는 개발자가 많은 것 같습니다! 하지만 편의성때문에 querySelector를 사용하는 개발자들도 있다고 합니다...!! 덕분에 좋은 정보를 알아갑니다!)

2023-07-16 13:05 UTC, SongInjae commented on src/Sidebar.js
> +    });
허걱쓰 감사합니다ㅠㅠㅠㅠㅠㅠ👊

2023-07-16 13:14 UTC, SongInjae commented on src/Sidebar.js
> +    });
네!! stopPropagation을 이용하여 기존의 이벤트 버블링을 제거하여 토글의 이벤트만 이뤄지도록 했습니다:)

2023-07-17 06:25 UTC, SongInjae commented on index.css
> +    /*background-color: lightgray;*/
감사합니다🥸🙏

2023-07-17 06:26 UTC, SongInjae commented on index.html
> +        <title>잉재의 노션 클로닝 프로젝트</title>
하하핳...🙈

2023-07-17 06:27 UTC, SongInjae commented on src/App.js
> +  if (check) {
네 맞습니다!! 혹시 더 좋은 방법이 있을까요?

2023-07-17 06:28 UTC, SongInjae commented on src/Content.js
> +        if (divElement.children[i].tagName === "SPAN") {
저도 찾아보니 이런 메소드도 있었습니다!저렇게 대문자로 쓰는

2023-07-17 06:42 UTC, SongInjae commented on src/Content.js
> +      for (let i = 0; i < divElement.children.length; i++) {
span에 도달한 이후에는 반복문이 굳이 돌 필요가 없어서 **break가 없는 forEach** 대신에 **for 반복문**을 사용했는데,
**간결성을 위해서 forEach문을 사용하는 것**이 더 좋을까요?

2023-07-17 06:44 UTC, backward99 commented on src/modal.js
> +  const $submitModal = document.getElementById("submit-modal");
인재님 코드 보고 다르게 적혀 있길래, 저도 잘 몰라서 찾아보게 되었습니다! 저도 덕분에 좋은 정보 알아갑니다!

2023-07-17 06:52 UTC, SongInjae commented on src/Content.js
> +          this.setState(nextState);
const가 블록스코프라 두 개로 분리해서 썼었는데,
더 깊게 생각해보니 삼항 연산자로 분리하면 유진님 말대로 한 번 작성해도 되는 것 같습니다!
역싀 최고십니다...⭐️

2023-07-17 06:54 UTC, SongInjae commented on src/Editor.js
> +    document.execCommand(e.target.getAttribute("data-command"));
저도 예전에 편집기 강의 들었을 때 **대애박** 하면서 들었던 거라 기억해서 썼었던건데
칭찬은 감사하게 받겠습니다🙈

2023-07-17 06:56 UTC, SongInjae commented on src/Sidebar.js
> +      onChange(e.target.parentNode.getAttribute("data-id"));
지호님 코드 반영하면서 함께 반영했습니다!
유진님 말씀대로 너무 길다면 변수에 정의해준 뒤에 파라미터로 넘겨주는 것이 좋은 것 같습니다:) 감사합니다🙏

2023-07-17 07:42 UTC, SongInjae commented on src/Sidebar.js
> +    });
오옹 toggle이라는 메소드가 있었군요!
기존에는 클래스이름에 직접 추가하고 삭제하는 방식으로 진행했었는데
이제는 클래스를 직접 추가 및 삭제할 때는 이 toggle메소드를 이용해봐야겠습니다!

2023-07-17 07:52 UTC, SongInjae commented on src/App.js
> +    $notionContent.style.display = "flex";
지금 notionContent의 경우에는 toggle형식으로 작동하기 보다는,
처음에만 none이였다가 사이드바의 제목을 한 번이라도 클릭하면 그 순간부터 계속 content가 보여주는 식으로 작동을 해서
toggle의 방식은 사용하지 않아도 될 것 같습니다!

하지만 sidebar가 버튼을 클릭하면 보여주고 다시 클릭하면 가리는 방식에서는 toggle메소드가 좋을 것 같습니다!
좋은 방법 알려주셔서 감사합니다😊

2023-07-17 08:06 UTC, SongInjae commented on src/Sidebar.js
> +}
buttonModal이 메인함수를 제외하고도 다른 함수에서 사용을해서 따로 빼뒀었습니다!

어떠한 함수가 메인함수의 스코프를 벗어나서 다른 함수에서도 쓰일 때만 따래 빼놔서 함수를 만들었는데,
정호님의 코드처럼 함수를 잘게잘게 나누는 작업이 저한테 필요할 것 같습니다!
저는 다른 곳에서 쓰이지 않으면 다 안에다가 넣어놨는데
한 함수의 코드가 너무 무거운 것 같습니다🥲

2023-07-17 08:17 UTC, SongInjae commented on src/modal.js
> +  $submitModal.addEventListener("click", () => {
너무 좋은 것 같습니다! 정호님 리뷰 반영완료했습니다:)😊

2023-07-17 09:26 UTC, SongInjae commented on index.html
> +</html>
아 HTML은 브라우저에서 랜더링 되는 부분이기때문에 HTML태그 사이에는 개행을 하지 않는군요! 
여태 모르고 계속 개행을 했던 것 같습니다🥲 감사합니다

2023-07-17 09:49 UTC, SongInjae commented on src/Content.js
> +  let timer = null;
timer 자체가 랜더링에 직접적으로 연관이 되어있지 않기 때문에 상태로 관리하지 않았습니다!
따로 상태로 관리해야할 대상일까요?

2023-07-17 09:51 UTC, SongInjae commented on src/Content.js
> +    timer = setTimeout(async () => {
넵! 그래서 setTimeout 안에서 이뤄지는 작업들을 따로 함수로 작업화하여,
어떤 작업들이 이뤄지는지 확인할 수 있도록 코드 반영했습니다:)
코드 작성하는데 급급해서 세세한 부분들은 신경쓰지 못했던 것 같습니다🥲
좋은 조언 감사합니다🙏

2023-07-17 09:56 UTC, SongInjae commented on src/Editor.js
> +  $target.appendChild($editor);
오호 append로도 자식요소에 추가할 수 있는지 몰랐습니다!
appendChild가 더 오래전에 나온 것이고, appendChild가 하나의 인자만을 받는 단점때문에
이를 보완하기 위해 append가 나왔군요!🥸
멘토님 덕분에 좋은 정보를 알아가는 것 같습니다! 감사합니다🙏

2023-07-17 10:14 UTC, merged

2023-07-22 11:44 UTC, pocojang commented on src/Content.js
> +  let timer = null;
그에 대한 기준이 명확히 보이지는 않네요?!